CREATE TABLE tcp_ports (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 port INTEGER NOT NULL UNIQUE CHECK(port BETWEEN 10000 AND 65535),
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX tcp_ports_user_id ON tcp_ports(user_id);
